packages:
  - client
  - server
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - bufferutil
  - esbuild
  - msgpackr-extract
  - prisma
  - utf-8-validate
